// app/layout.tsx
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { SidebarProvider, SidebarTrigger, SidebarInset } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { Separator } from "@/components/ui/separator";
import { ActiveChannelProvider } from "@/context/ActiveChannelContext";
import { AuthProvider } from "@/context/AuthContext";
const outfitSans = Outfit({
  variable: "--font-outfit-sans",
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfitSans.className} antialiased`}>
        
        <AuthProvider>
        <ActiveChannelProvider>
        <Navbar />
        <SidebarProvider defaultOpen={false}>
          {/* Layout horizontal avec sidebar et contenu */}
          <div className="flex min-h-screen pt-16 w-full"> {/* pt-16 pour laisser l'espace de la navbar si fixe */}
            {/* Sidebar */}
            <AppSidebar />

            {/* Contenu principal avec trigger */}
            <SidebarInset className="flex-1 flex flex-col overflow-auto">
              <header className="flex h-16 items-center gap-2 px-4 bg-white dark:bg-black shrink-0">
                <SidebarTrigger className="-ml-1" />
                <Separator orientation="vertical" className="mr-2 h-8" />
              </header>

              {/* Main content ici */}
              <main className="flex-1 p-4">{children}</main>
            </SidebarInset>
          </div>
        </SidebarProvider>
        </ActiveChannelProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
